name: imagenes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0 # librería para ocultar .env (donde tenemos las variables de entorno)

  cupertino_icons: ^1.0.8 # esta librería trae los íconos Cupertino
  font_awesome_flutter: ^10.9.1 # esta libreria trae los iconos de Awesome
  cloudinary_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - dev.env
    - assets/images/
